export function get_all_tags() {
	return [
		'3D Animation',
		'3D Modeling',
		'Visualization',
		'Architecture',
		'Engineering',
		'Hands-on',
		'Presentation',
		'Creative Writing',
		'Culture',
		'History of Art',
		'Dance',
		'Performing',
		'Merchandising',
		'Fashion',
		'Business Development',
		'Business Management',
		'Game Design',
		'Game Development',
		'Interface Design',
		'User Experience',
		'Decorating',
		'Material Selection',
		'Music Production',
		'Photography',
		'Storytelling',
		'Filmmaking',
		'Video Editing',
		'AR/VR',
		'Motion Capture',
		'Print Design',
		'Product Development',
		'Material Design',
		'Space Planning'
	];
}